export const ShirtData = [
  {
    id: '0001',
    url: require('../images/0001_fashion_image.jpg'),
    price: 24.99,
    model: 'V Neck Shirt',
    raiting: 4.9,
    color: 'grey',
  },
  {
    id: '0002',
    url: require('../images/0002_fashion_image.jpg'),
    price: 24.9,
    model: 'V Neck Shirt',
    raiting: 4.7,
    color: 'grey',
  },
  {
    id: '0003',
    url: require('../images/0003_fashion_image.jpg'),
    price: 24.99,
    model: 'Round Neck Shirt',
    raiting: 4.8,
    color: 'brown',
  },
  {
    id: '0004',
    url: require('../images/0004_fashion_image.jpg'),
    price: 24.99,
    model: 'V Neck Shirt',
    raiting: 4.5,
    color: 'green',
  },
  {
    id: '0005',
    url: require('../images/0005_fashion_image.jpg'),
    price: 24.9,
    model: 'V Neck Shirt',
    raiting: 4.7,
    color: 'pink',
  },
  {
    id: '0006',
    url: require('../images/0006_fashion_image.jpg'),
    price: 24.99,
    model: 'Round Neck Shirt',
    raiting: 4.9,
    color: 'green',
  },
  {
    id: '0007',
    url: require('../images/0007_fashion_image.jpg'),
    price: 23.99,
    model: 'V Neck Shirt',
    raiting: 4.9,
    color: 'green',
  },
  {
    id: '0008',
    url: require('../images/0008_fashion_image.jpg'),
    price: 20.99,
    model: 'V Neck Shirt',
    raiting: 4.6,
    color: 'white',
  },
  {
    id: '0009',
    url: require('../images/0009_fashion_image.jpg'),
    price: 24.99,
    model: 'Round Neck Shirt',
    raiting: 4.9,
    color: 'pink',
  },
  {
    id: '0010',
    url: require('../images/0010_fashion_image.jpg'),
    price: 24.99,
    model: 'V Neck Shirt',
    raiting: 4.5,
    color: 'green',
  },
  {
    id: '0011',
    url: require('../images/0011_fashion_image.jpg'),
    price: 18.99,
    model: 'V Neck Polo Shirt',
    raiting: 4.4,
    color: 'orange',
  },
  {
    id: '0012',
    url: require('../images/0012_fashion_image.jpg'),
    price: 24.99,
    model: 'V Neck Shirt',
    raiting: 4.7,
    color: 'red',
  },
  {
    id: '0013',
    url: require('../images/0013_fashion_image.jpg'),
    price: 30.99,
    model: 'V Neck Polo Shirt',
    raiting: 4.9,
    color: 'orange',
  },
  {
    id: '0014',
    url: require('../images/0014_fashion_image.jpg'),
    price: 24.99,
    model: 'V Neck Shirt',
    raiting: 4.9,
    color: 'grey',
  },
  {
    id: '0015',
    url: require('../images/0015_fashion_image.jpg'),
    price: 24.99,
    model: 'V Neck Shirt',
    raiting: 4.8,
    color: 'yellow',
  },
];
